version: '3.10'

services:
  app:
    build: ./
    volumes:
      - ./:/app
    #            - /home/tema/CODE/AtomHack_Submit/data/FINISH:/SG/dataset

    ports:
      - 8501:8501
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockage1.entrypoints=web, websecure"
      - "traefik.http.routers.dockage1.rule=Host(`techshtormhack.medpaint.ru`)"
      - "traefik.http.routers.dockage1.tls=true"
      - "traefik.http.routers.dockage1.tls.certresolver=production"
      - "traefik.tcp.services.kafka-broker.loadbalancer.server.port=8501"

    #        image: submit:latest

    command: >
      bash -c "streamlit run main.py"

networks:
  default:
    name: traefik
    external: true
