version: '3.10'

services:
  app:
    build: ./
    volumes:
      - ./:/app
    #            - /home/tema/CODE/AtomHack_Submit/data/FINISH:/SG/dataset

    ports:
      - 8501:8501

    #        image: submit:latest

    command: >
      bash -c "python loop.py"

#            bash -c "python submit.py"

#
#        environment:
#            - NVIDIA_VISIBLE_DEVICES=all
#        deploy:
#          mode: replicated
#          replicas: 1
#          resources:
#            reservations:
#              devices:
#                - driver: nvidia
#                  device_ids: [ '0' ]
#                  capabilities: [ gpu ]
#
